import os

APP_VERSION = os.getenv("LANLENS_APP_VERSION", "1.5.7")
BUILD_CODE = os.getenv("LANLENS_BUILD_CODE", "20260611.1055")
BUILD_COMMIT = os.getenv("LANLENS_BUILD_COMMIT", "unknown")
BUILD_BRANCH = os.getenv("LANLENS_BUILD_BRANCH", "unknown")
BUILD_CREATED = os.getenv("LANLENS_BUILD_CREATED", "unknown")
