export const APP_VERSION = '1.5.4'
export const GITHUB_REPO = 'AlexRosbach/LanLens'
export const BUILD_CODE = import.meta.env.VITE_LANLENS_BUILD_CODE || '1.5.4-b9a8afb9eae2'
export const BUILD_COMMIT = import.meta.env.VITE_LANLENS_BUILD_COMMIT || 'b9a8afb9eae289f0dee49101e475ad2c6f99c00e'
export const BUILD_BRANCH = import.meta.env.VITE_LANLENS_BUILD_BRANCH || 'codex/1.5.4-plugin-api-discovery'
export const BUILD_CREATED = import.meta.env.VITE_LANLENS_BUILD_CREATED || '2026-05-30T22:06:24Z'
